# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m-ZtOF5jF4JClj8ZQug52P6JuvP3aqsm
"""

import pandas as pd
import matplotlib.pyplot as plt

# Carregar o arquivo CSV (substitua pelo caminho correto)
df = pd.read_csv("tabela_fipe_carros.csv")

# Exibir as primeiras linhas para entender os dados
print(df.head())

# Ajustando nomes das colunas (removendo espaços extras caso existam)
df.columns = df.columns.str.strip()

# Convertendo o ano_modelo para número
df["ano_modelo"] = pd.to_numeric(df["ano_modelo"], errors="coerce")

# Lista de modelos para comparar
modelos = ["Eurovan 2.4", "Gol 1.0", "Golf 2.0", "Palio 1.0", "Fusca", "Sedan 2.0 "]

# Criar gráfico para todos os modelos
plt.figure(figsize=(10, 5))

for modelo in modelos:
    df_modelo = df[df["modelo"].str.contains(modelo, case=False, na=False)]
    df_modelo = df_modelo.sort_values(by="ano_modelo", ascending=True)

    if not df_modelo.empty:
        plt.plot(df_modelo["ano_modelo"], df_modelo["valor"], marker="o", linestyle="-", label=modelo)

# Personalizar o gráfico
plt.xlabel("Ano do Modelo")
plt.ylabel("Preço na Tabela FIPE")
plt.title("Comparação de Depreciação de Modelos")
plt.legend()
plt.grid()
plt.show()